language: python
jobs:
  include:
    - name: "Linux"
      python: 3.9
    - name: "MacOS"
      os: osx
      osx_image: xcode12.2
      language: shell
install:
  - make clean
script:
  - make test
