from typing import Any

class Ui_MainWindow:
    centralwidget: Any = ...
    verticalLayout: Any = ...
    group_file_selection: Any = ...
    gridLayout: Any = ...
    label_input_status: Any = ...
    field_image: Any = ...
    button_image: Any = ...
    field_input: Any = ...
    button_input: Any = ...
    label_output: Any = ...
    field_output: Any = ...
    label_image_status: Any = ...
    button_output: Any = ...
    label_output_status: Any = ...
    label_image: Any = ...
    label_input: Any = ...
    group_parametre: Any = ...
    gridLayout_2: Any = ...
    field_authkey: Any = ...
    check_stdout: Any = ...
    spin_compress: Any = ...
    group_action: Any = ...
    horizontalLayout: Any = ...
    button_create: Any = ...
    button_extract: Any = ...
    button_clear: Any = ...
    label_compress: Any = ...
    spin_density: Any = ...
    label_density: Any = ...
    check_showim: Any = ...
    label_authkey: Any = ...
    group_output: Any = ...
    gridLayout_4: Any = ...
    text_output: Any = ...
    menubar: Any = ...
    menu_file: Any = ...
    toolBar: Any = ...
    action_help: Any = ...
    action_close: Any = ...
    def setupUi(self, MainWindow: Any) -> None: ...
    def retranslateUi(self, MainWindow: Any) -> None: ...
