from PyQt5 import QtWidgets
from StegLibrary.core.errors import SteganographyError as SteganographyError, UnrecognisedHeaderError as UnrecognisedHeaderError
from StegLibrary.core.steg import extract_header as extract_header, extract_steg as extract_steg, write_steg as write_steg
from StegLibrary.gui import Ui_MainWindow as Ui_MainWindow
from StegLibrary.helper import err_imp as err_imp, raw_open as raw_open
from typing import Any

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args: Any, obj: Any=..., **kwargs: Any) -> None: ...
    has_steg: bool = ...
    has_data: bool = ...
    has_image: bool = ...
    has_output: bool = ...
    input_filename: str = ...
    output_filename: str = ...
    image_filename: str = ...
    def reset(self) -> None: ...
    def register_logic(self): ...
    input_fileobject: Any = ...
    def select_input(self) -> None: ...
    image_fileobject: Any = ...
    def select_image(self) -> None: ...
    output_fileobject: Any = ...
    def select_output(self) -> None: ...
    def create(self) -> None: ...
    def extract(self) -> None: ...
    def print_system_status(self) -> None: ...
    def enable_parametres(self) -> None: ...
    def disable_parametres(self) -> None: ...
    def write_output(self, msg: str) -> Any: ...
    def fallback(self) -> None: ...
