from typing import List

class SteganographyConfig:
    available_compression: List[int] = ...
    available_density: List[int] = ...
    default_compression: int = ...
    default_density: int = ...
    default_auth_key: str = ...
    flag_close_on_exit: bool = ...
    flag_show_image_on_completion: bool = ...
    flag_fopen_mode: bool = ...
