class SteganographyError(BaseException): ...
class InputFileError(SteganographyError): ...
class OutputFileError(SteganographyError): ...
class InsufficientStorageError(SteganographyError): ...
class UnrecognisedHeaderError(SteganographyError): ...
class AuthenticationError(SteganographyError): ...
