from StegLibrary.core.errors import UnrecognisedHeaderError as UnrecognisedHeaderError
from re import Pattern as Pattern
from typing import Any

class Header:
    padding_character: str = ...
    separator: str = ...
    maximum_data_length: int = ...
    maximum_flag_length: int = ...
    salt_length: int = ...
    separator_length: int = ...
    header_length: int = ...
    pattern: str = ...
    hash_pattern: str = ...
    data_length: Any = ...
    compression: Any = ...
    density: Any = ...
    salt: Any = ...
    def __init__(self, data_length: int, compression: int, density: int, salt: str) -> None: ...
    header: Any = ...
    def generate(self) -> None: ...

def build_header(data_length: int, *, compression: int=..., density: int=..., salt: str) -> Header: ...
def validate_header(b: bytes) -> bool: ...
def parse_header(b: bytes) -> Header: ...
