from StegLibrary.core.steg import extract_steg as extract_steg, write_steg as write_steg
from StegLibrary.gui import execute_gui as execute_gui
from StegLibrary.helper import err_imp as err_imp, open_image as open_image, raw_open as raw_open
from typing import Any

def steg() -> None: ...
def create(image: str, key: str, compress: int, pack: int, output: str, showim: bool, data: str) -> Any: ...
def extract(key: str, output: str, stdout: bool, steganograph: str) -> Any: ...
def gui() -> None: ...
