from typing import Optional

def is_bit_set(i: int, pos: int) -> bool: ...
def set_bit(i: int, pos: int) -> int: ...
def unset_bit(i: int, pos: int) -> int: ...
def bitstr_from_int(i: int, length: Optional[int]=...) -> str: ...
def int_from_bit_str(s: str) -> int: ...
