from typing import Any

class ANSIFormatter:
    ColourTemplate: str = ...
    Reset: str = ...
    Black: str = ...
    Red: str = ...
    Green: str = ...
    Yellow: str = ...
    Blue: str = ...
    Magenta: str = ...
    Cyan: str = ...
    White: str = ...
    BrightBlack: str = ...
    BrightRed: str = ...
    BrightGreen: str = ...
    BrightYellow: str = ...
    BrightBlue: str = ...
    BrightMagenta: str = ...
    BrightCyan: str = ...
    BrightWhite: str = ...
    BackgroundBlack: str = ...
    BackgroundRed: str = ...
    BackgroundGreen: str = ...
    BackgroundYellow: str = ...
    BackgroundBlue: str = ...
    BackgroundMagenta: str = ...
    BackgroundCyan: str = ...
    BackgroundWhite: str = ...
    BackgroundBrightBlack: str = ...
    BackgroundBrightRed: str = ...
    BackgroundBrightGreen: str = ...
    BackgroundBrightYellow: str = ...
    BackgroundBrightBlue: str = ...
    BackgroundBrightMagenta: str = ...
    BackgroundBrightCyan: str = ...
    BackgroundBrightWhite: str = ...
    Bold: str = ...
    Underline: str = ...
    Reversed: str = ...
    @staticmethod
    def generate256bitColour(code: str) -> str: ...
    @staticmethod
    def generate256bitBackgroundColour(code: str) -> str: ...
    @staticmethod
    def is_ansi_code(code: str) -> bool: ...
    @staticmethod
    def extendedPrint(obj: Any, *args: Any, **kwargs: Any) -> None: ...

def err_imp(pkg_name: str) -> None: ...
